version: '3.8'
services:
 server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - client

 client:
    build: ./client
    ports:
      - "5173:80"
    volumes:
      - ./client:/app
